Creating tool to add data to new INFO field
griffithlab/VAtools pull request #1
Opened 2018-07-18 18:43 UTC by chrisamiller

2018-07-19 18:17 UTC, susannasiebert requested changes
If you want to make this accessible on the command line you will need to add an entry to the entry_point->console_scripts array in setup.py.

2018-07-19 18:17 UTC, susannasiebert commented on vcf_annotation_tools/vcf_info_annotator.py
> +    parser = argparse.ArgumentParser("vcf-generic-annotator")
What do you want the entry point to be names? Here it's `vcf-generic-annotator` but the file and class is VcfInfoAnnotator. This should be consistent.

2018-07-23 23:07 UTC, chrisamiller commented
Just pushed fixes to both of those issues

2018-07-30 03:16 UTC, chrisamiller commented
Pinging @susannasiebert before merging

2018-07-31 15:30 UTC, susannasiebert approved these changes

2018-07-31 15:32 UTC, susannasiebert commented
Looks good to me. The only other thing that would be great is to add a test case to check that the annotation actually works.

2018-08-08 14:34 UTC, susannasiebert approved these changes
+1 once tests pass. Thanks for this addition to the package.

2018-08-08 14:34 UTC, merged