clarify input format
griffithlab/VAtools pull request #24
Opened 2019-04-05 04:16 UTC by chrisamiller

It would also be nice to add this detail to the vatools.org help page - took me a bit of trial-and-error to figure it out!

2019-04-05 13:49 UTC, susannasiebert commented
You don't actually need to specify them this way (although it works). The "default" way is space separated, no quotes, no curly braces.

2019-04-05 14:04 UTC, chrisamiller commented
Oh wow, okay - that really confused me, as I'm used to bash/perl conventions where space separated means separate parameters.  Is that a standard pythonic convention?  Is adding "space separated list" to the help line a reasonable thing to do, or is that really fundamental and assumed by everyone else?

2019-04-05 14:09 UTC, susannasiebert commented
At least when using argparse (which is the recommended argument parser), yes. In the help note the following:
```
$ vep-annotation-reporter -h
usage: vep-annotation-reporter [-h] [-t INPUT_TSV] [-o OUTPUT_TSV]
                               input_vcf vep_fields [vep_fields ...]
```
`vep_fields [vep_fields ...]`
This means the first vep_fields VEP field is required, followed by an optional second one (the square braces) or more (the `...`). They are all separated by spaces.

2019-04-05 14:14 UTC, susannasiebert commented
btw, I believe that the reason your first suggestion works, is because bash converts it to a space separated list
```
$ echo {'Consequence','SYMBOL','Feature','HGVSc','HGVSp'}
Consequence SYMBOL Feature HGVSc HGVSp
```

2019-04-05 14:18 UTC, susannasiebert requested changes

2019-04-05 14:18 UTC, susannasiebert commented on vatools/vep_annotation_reporter.py
> +            +"curly brackets. Example: {'Consequence','SYMBOL','Feature','HGVSc','HGVSp'}"
This line is missing a comma at the end, causing a syntax error.

2019-04-05 14:20 UTC, chrisamiller commented
Got it - that totally wasn't clear to me, but I guess it is documented.  I edited this change to the help text. Maybe also worth adding something like the below to this page? https://vatools.readthedocs.io/en/latest/vep_annotation_reporter.html


**Example command:**

    vep-annotation-reporter input.vcf Consequence SYMBOL Feature -t input.table -o output.table

2019-04-05 14:20 UTC, susannasiebert approved these changes
+1

2019-04-05 14:23 UTC, susannasiebert commented
> Maybe also worth adding something like the below to this page? https://vatools.readthedocs.io/en/latest/vep_annotation_reporter.html
> 
> **Example command:**
> 
> ```
> vep-annotation-reporter input.vcf Consequence SYMBOL Feature -t input.table -o output.table
> ```

Agreed. Do you want to take a stab at that or should I? Btw, the command line help docs change wouldn't take effect until I make a new version and I think just this change is not worth a new release. Docs changes will take effect (almost) immediately it gets merged to master.

2019-04-05 14:26 UTC, chrisamiller commented
I'm going to guess that you could drop it into the docs in like 3 minutes, and it'd take me 15 minutes of figuring out where to start, so if you wouldn't mind...

Yeah, agree that this doesn't need a new release!

2019-04-05 14:26 UTC, merged

2019-04-08 13:34 UTC, tmooney commented
If I may be nitpicky, it doesn't *really* take a space-separated list.  It takes multiple arguments, and  arguments are often separated by spaces in the shell.  But
```perl
system('vep-annotation-reporter','input.vcf','Consequence','SYMBOL','Feature','-t','input.table','-o','output.table');
```
has no spaces in it at all, and is equivalent to the example bash line in a previous comment.
This passes a space-separated list:
```perl
system('vep-annotation-reporter','input.vcf','Consequence SYMBOL Feature','-t','input.table','-o','output.table');
```
or the bash equivalent:
```bash
vep-annotation-reporter input.vcf 'Consequence SYMBOL Feature' -t input.table -o output.table
```